### PR TITLE
Provide a way to allow reverse proxies & https

### PR DESCRIPTION
**Pull request by mikedevita**
## explanation
I run nginx at home to proxy all of my web traffic, and drop an ssl in front of everything. 

if you drop an SSL nginx reverse proxy infront of OSPi two defects occur.

1. you are redirected to the `http://<hostname>/login` instead of `https://<hostname>/login`
2. some/most of the static assets are loaded via `http://`, when really they should be loaded with `//`, this will allow them to be loaded for both https and http.

## Steps to reproduce
1. put an ssl nginx reverse proxy in front of the OSPi interface.
2. visit the proxied url (in my case https://sprinkler.domain.com), it will redirect to `http://<hostname>/login`
3. force that URL to be `https://<hostname>/login` and none of the static assets will load.

I would be happy to fork, and attempt to fix these two things and issue a PR.

## potential root cause
After digging a bit I think this block is whats causing the issues, `wsgi.url_scheme` is always `http` because it doesn't know how to interpret the `X-Forwarded-Proto` header. 

```python
        if env.get('wsgi.url_scheme') in ['http', 'https']:
            ctx.protocol = env['wsgi.url_scheme']
        elif env.get('HTTPS', '').lower() in ['on', 'true', '1']:
            ctx.protocol = 'https'
        else:
            ctx.protocol = 'http'
```

## potential fix
1. for the redirect issue, adding a conditional statement to check for the `X-Forwarded-Proto` header should work sufficiently. 
2. For the static assets, i'd think moving them to absolute paths instead of `http://....` would work fine as well.
3. for google fonts in the base.css, just moving that to use `https` by default should work fine

**web/application.py**
```python
        if env.get('HTTP_X_FORWARDED_PROTO') in ['http', 'https']:
            ctx.protocol = env.get('HTTP_X_FORWARDED_PROTO')
        elif env.get('wsgi.url_scheme') in ['http', 'https']:
            ctx.protocol = env['wsgi.url_scheme']
        elif env.get('HTTPS', '').lower() in ['on', 'true', '1']:
            ctx.protocol = 'https'
        else:
            ctx.protocol = 'http'
```

**templates/base.html**
```
    <link href="/static/them......
```

### CODE REVIEW

**Comment by mikedevita** [comment]
I am still working out how to get web.py to quit forcing redirects to `http://`. It seems we need some way of checking the protocol with `web.ctx.protocol` (i'm guessing) and then using that.

**Comment by mikedevita** [comment]
pretty sure its fixed now. Not sure if its how you'd like it down, let me know your thoughts.

**Comment by Dan-in-CA** [comment]
Thanks for your work on this. 
I would like to test your fixes before merging but I am in the middle of some intense dev work. It may be a couple of days.

**Comment by Dan-in-CA** [comment]
Hi Mike,
After giving this more thought I'm wondering if this is the best way to go. 
You mentioned an 'nginx box' which indicates that you are not running nginx on the Pi. I have messed around with nginx as a reverse proxy running on the Pi and it worked great.

Another approach is to replace the development server that webpy uses with nginx as described on the wiki:
http://rayshobby.net/mediawiki/index.php?title=Secure_Remote_Access

It seems like forcing the default server to serve https would not really provide the necessary security.

**Comment by mikedevita** [comment]
Hey Dan, not sure what you mean by forcing https? All its doing is checking for `x-forwarded-for` and making sure the server doesn't redirect to http when clearly its being served up over https. 

Although the section of that wiki about editing the `baseurl` should work fine for my needs as this is already what I am trying to accomplish. The only difference between my scenario and that wiki is nginx is on a different server.

I suppose this PR can be closed.

**Comment by Dan-in-CA** [comment]
Mike,
I apologize. I misunderstood what you were doing.
As you can tell, my knowledge of network security is not what it should be. I would still like to include your changes into the OSPi distribution..

It is great timing that you pointed out that gv.baseurl does nothing. it was probably the first or second var that was defined when this project was started a couple of years ago. It seemed like a good idea at the time. It will be completely removed from the next update.

I am starting to add a bunch of HTML help files to be served from the static dir and had been putting gv.baseurl at the start of each link

Dan

**Comment by mikedevita** [comment]
No problem Dan, let me know if you need anymore from me on this. I am always HTH.

I am noobish when it comes to Python, but excel in php, nodejs, and front-end stuff like angularjs html5,css3

**Pull request merged**
