### PR TITLE
Reverse proxy

### PR DESCRIPTION
**Pull request by cbright**
Added support for hosting OSPi in a subdirectory instead of the root of a domain such as https://FQDN/ospi/ by updating link generation to respect the web.ctx.homepath variable. Also supports SSL offloading from a reverse proxy but I believe this is already supported.

This is accomplished by reading a HTTP_X_SCRIPT_NAME head and setting the environ['SCRIPT_NAME'] variable and is based on the implementation found in the [OctoPrint project](https://github.com/foosel/OctoPrint/blob/master/src/octoprint/server/util.py#L332). Web.py then binds this to [web.ctx.homepath variable](http://webpy.org/cookbook/ctx) and is used throughout the html templates to prefix any hardcoded urls and static resources.

The default plugins will work but any plugins used in conjunction with a subdirectory will need to be updated to support generating links with $app_path('url') or the global baseUrl js var for any hardcoded urls. Plugins should still work if the app is still hosted at the root. (ie '/')

### CODE REVIEW

**Comment by Dan-in-CA** [comment]
Thank you for the input the the project. I will need to do some testing before mreging.

**Comment by cbright** [comment]
Is there anything I can do to help get this accepted? I would like to get my ospi back onto master.

**Comment by Dan-in-CA** [comment]
Sorry for the delay,
I am in the process of renaming the project to avoid confusion with Ray's now commercial OpenSprinkler product. It will be renamed to SIP in stead of OSPi.

Because users have a varying  range of knowledge and experience I was thinking it would be very helpful if you could write some documentation for setting up a reverse proxy. It would be added to the documentation on the GitHub wiki for the project which is now linked from a help button in the UI.

**Comment by cbright** [comment]
I added some documentation. Setting up a reverse proxy probably falls under the "advanced user" category, but I'm open to any feedback to make it easier to understand.

**Comment by Dan-in-CA** [comment]
Excellent!

Thanks again for your contribution to the project. I plan to make an announcement on the forum including the name change on June 9 which will be the 2 year anniversary of the initial release.

I haven't looked at your documentation yet. I will provide feedback as soon as i have a chance. Thing are pretty hectic right now.

**Pull request merged**
